### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by linean** [mfaella/JLiquidFun#1]
Can you write some sample code, how I can use that. That would be a huge help :)

**Comment by mfaella** [comment]
A full project using this library is in this other repository: https://github.com/mfaella/DragMe

**DragMe** is a simulation of rigid bodies for **Android**.
Bodies can be dragged around and are subject to gravity,
whose direction is aligned to the earth via accelerometer data.

**Comment by linean** [comment]
Thanks ! :)
